name: diox_example
description: The example snippets for Dio.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cookie_jar:
  crypto:
  diox:
  diox_cookie_manager:
    path: ../plugins/cookie_manager
  diox_http2_adapter:
    path: ../plugins/http2_adapter

dependency_overrides:
  diox:
    path: ../dio

dev_dependencies:
  lints: any
  test: ^1.22.1
