name: dio
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 5.0.0-dev.2
homepage: https://github.com/flutterchina/dio

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  lints: any
  test: ^1.5.1
  coverage: ^1.0.3
  crypto: ^3.0.2
