name: Dio

on:
  push:
    branches:
      - main
      - develop*
  pull_request:
    branches:
      - main
      - develop*

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dio
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart analyze

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dio
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart format --set-exit-if-changed .

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ stable, beta ]
        platform: [ vm, chrome ]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: |
          chmod +x ./scripts/prepare_pinning_certs.sh
          ./scripts/prepare_pinning_certs.sh
        shell: bash
      - run: cd dio && dart pub get
      - run: cd dio && dart test --chain-stack-traces --platform=${{ matrix.platform }}

  publish-dry-run:
    name: Publish dry-run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dio
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart pub publish --dry-run
