name: native_diox_adapter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins/native_diox_adapter
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
      - run: flutter pub get
      - run: flutter analyze

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins/native_diox_adapter
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed .

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ stable, beta ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.sdk }}

  publish-dry-run:
    name: Publish dry-run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins/http2_adapter
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
      - run: flutter pub get
      - run: flutter pub publish --dry-run
